{
    "code": 0,
    "msg": "成功",
    "result": {
        "skuIds": [
            1001593
        ],
        "pictures": {
            "1001593": "http://storage.jd.com/b2b.jcloud.jd.com/20151102173702441"
        },
        "orderList": {
            "orders": [
                {
                    "platformId": 2,
                    "sellerId": 1001166,
                    "orderId": 1000697,
                    "buyerId": 1001282,
                    "shopId": 1000160,
                    "name": "党源潮",
                    "provinceId": "11",
                    "cityId": "1101",
                    "countyId": "110101",
                    "detailAddress": "北辰世纪中心a座",
                    "fullAddress": "北京市市辖区东城区北辰世纪中心a座",
                    "mobile": "18513955321",
                    "phone": null,
                    "email": null,
                    "orderTime": 1452149921000,
                    "orderFinishTime": null,
                    "totalPrice": 4000,
                    "totalDiscount": 10,
                    "freight": 5,
                    "paymentPrice": 3995,
                    "state": 10,
                    "yn": 1,
                    "operations": [],
                    "orderJfsKey": "http://192.168.150.52/fw.jd.com/20160107145859130?Expires=1609829939&AccessKey=CGZmtRcoyB7pzdPu&Signature=iqg0LwKnzNlZYVKQWRSVyL5UBbg%3D",
                    "createTime": 1452149360000,
                    "updateTime": 1452149360000,
                    "cancelTime": null,
                    "memo": "",
                    "invoice": 1,
                    "invoiceTitle": null,
                    "parentOrderId": 1000695,
                    "logisticsNo": null,
                    "logisticsCompany": null,
                    "items": [
                        {
                            "id": 1000863,
                            "platformId": 2,
                            "orderId": 1000697,
                            "skuId": 1001593,
                            "itemId": 1001185,
                            "skuName": "乐视超级电视 S40 Air 全配版 智能LED液晶",
                            "primitivePrice": 5196,
                            "num": 4,
                            "areaId": 0,
                            "promotionType": 0,
                            "promotionDiscount": 0,
                            "promotionId": 0,
                            "createTime": 1452149921000,
                            "updateTime": null
                        }
                    ],
                    "paymentType": null,
                    "paymentTime": null,
                    "deleted": 1,
                    "deleteTime": null,
                    "locked": 1,
                    "lockTime": null,
                    "refund": 1,
                    "refundTime": null,
                    "delay": 1,
                    "delayOverTime": null,
                    "evaluate": 1,
                    "sellerEvaluate": 2,
                    "afterService": 1
                },
                {
                    "platformId": 2,
                    "sellerId": 1001166,
                    "orderId": 1000697,
                    "buyerId": 1001282,
                    "shopId": 1000160,
                    "name": "党源潮",
                    "provinceId": "11",
                    "cityId": "1101",
                    "countyId": "110101",
                    "detailAddress": "北辰世纪中心a座",
                    "fullAddress": "北京市市辖区东城区北辰世纪中心a座",
                    "mobile": "18513955321",
                    "phone": null,
                    "email": null,
                    "orderTime": 1452149921000,
                    "orderFinishTime": null,
                    "totalPrice": 4000,
                    "totalDiscount": 10,
                    "freight": 5,
                    "paymentPrice": 3995,
                    "state": 20,
                    "yn": 1,
                    "operations": [],
                    "orderJfsKey": "http://192.168.150.52/fw.jd.com/20160107145859130?Expires=1609829939&AccessKey=CGZmtRcoyB7pzdPu&Signature=iqg0LwKnzNlZYVKQWRSVyL5UBbg%3D",
                    "createTime": 1452149360000,
                    "updateTime": 1452149360000,
                    "cancelTime": null,
                    "memo": "",
                    "invoice": 1,
                    "invoiceTitle": null,
                    "parentOrderId": 1000695,
                    "logisticsNo": null,
                    "logisticsCompany": null,
                    "items": [
                        {
                            "id": 1000863,
                            "platformId": 2,
                            "orderId": 1000697,
                            "skuId": 1001593,
                            "itemId": 1001185,
                            "skuName": "乐视超级电视 S40 Air 全配版 智能LED液晶",
                            "primitivePrice": 5196,
                            "num": 4,
                            "areaId": 0,
                            "promotionType": 0,
                            "promotionDiscount": 0,
                            "promotionId": 0,
                            "createTime": 1452149921000,
                            "updateTime": null
                        }
                    ],
                    "paymentType": null,
                    "paymentTime": null,
                    "deleted": 1,
                    "deleteTime": null,
                    "locked": 1,
                    "lockTime": null,
                    "refund": 1,
                    "refundTime": null,
                    "delay": 1,
                    "delayOverTime": null,
                    "evaluate": 1,
                    "sellerEvaluate": 2,
                    "afterService": 1
                },
                {
                    "platformId": 2,
                    "sellerId": 1001166,
                    "orderId": 1000697,
                    "buyerId": 1001282,
                    "shopId": 1000160,
                    "name": "党源潮",
                    "provinceId": "11",
                    "cityId": "1101",
                    "countyId": "110101",
                    "detailAddress": "北辰世纪中心a座",
                    "fullAddress": "北京市市辖区东城区北辰世纪中心a座",
                    "mobile": "18513955321",
                    "phone": null,
                    "email": null,
                    "orderTime": 1452149921000,
                    "orderFinishTime": null,
                    "totalPrice": 4000,
                    "totalDiscount": 10,
                    "freight": 5,
                    "paymentPrice": 3995,
                    "state": 30,
                    "yn": 1,
                    "operations": [],
                    "orderJfsKey": "http://192.168.150.52/fw.jd.com/20160107145859130?Expires=1609829939&AccessKey=CGZmtRcoyB7pzdPu&Signature=iqg0LwKnzNlZYVKQWRSVyL5UBbg%3D",
                    "createTime": 1452149360000,
                    "updateTime": 1452149360000,
                    "cancelTime": null,
                    "memo": "",
                    "invoice": 1,
                    "invoiceTitle": null,
                    "parentOrderId": 1000695,
                    "logisticsNo": null,
                    "logisticsCompany": null,
                    "items": [
                        {
                            "id": 1000863,
                            "platformId": 2,
                            "orderId": 1000697,
                            "skuId": 1001593,
                            "itemId": 1001185,
                            "skuName": "乐视超级电视 S40 Air 全配版 智能LED液晶",
                            "primitivePrice": 5196,
                            "num": 4,
                            "areaId": 0,
                            "promotionType": 0,
                            "promotionDiscount": 0,
                            "promotionId": 0,
                            "createTime": 1452149921000,
                            "updateTime": null
                        }
                    ],
                    "paymentType": null,
                    "paymentTime": null,
                    "deleted": 1,
                    "deleteTime": null,
                    "locked": 1,
                    "lockTime": null,
                    "refund": 1,
                    "refundTime": null,
                    "delay": 1,
                    "delayOverTime": null,
                    "evaluate": 1,
                    "sellerEvaluate": 2,
                    "afterService": 1
                },
                {
                    "platformId": 2,
                    "sellerId": 1001166,
                    "orderId": 1000697,
                    "buyerId": 1001282,
                    "shopId": 1000160,
                    "name": "党源潮",
                    "provinceId": "11",
                    "cityId": "1101",
                    "countyId": "110101",
                    "detailAddress": "北辰世纪中心a座",
                    "fullAddress": "北京市市辖区东城区北辰世纪中心a座",
                    "mobile": "18513955321",
                    "phone": null,
                    "email": null,
                    "orderTime": 1452149921000,
                    "orderFinishTime": null,
                    "totalPrice": 4000,
                    "totalDiscount": 10,
                    "freight": 5,
                    "paymentPrice": 3995,
                    "state": 99,
                    "yn": 1,
                    "operations": [],
                    "orderJfsKey": "http://192.168.150.52/fw.jd.com/20160107145859130?Expires=1609829939&AccessKey=CGZmtRcoyB7pzdPu&Signature=iqg0LwKnzNlZYVKQWRSVyL5UBbg%3D",
                    "createTime": 1452149360000,
                    "updateTime": 1452149360000,
                    "cancelTime": null,
                    "memo": "",
                    "invoice": 1,
                    "invoiceTitle": null,
                    "parentOrderId": 1000695,
                    "logisticsNo": null,
                    "logisticsCompany": null,
                    "items": [
                        {
                            "id": 1000863,
                            "platformId": 2,
                            "orderId": 1000697,
                            "skuId": 1001593,
                            "itemId": 1001185,
                            "skuName": "乐视超级电视 S40 Air 全配版 智能LED液晶",
                            "primitivePrice": 5196,
                            "num": 4,
                            "areaId": 0,
                            "promotionType": 0,
                            "promotionDiscount": 0,
                            "promotionId": 0,
                            "createTime": 1452149921000,
                            "updateTime": null
                        }
                    ],
                    "paymentType": null,
                    "paymentTime": null,
                    "deleted": 1,
                    "deleteTime": null,
                    "locked": 1,
                    "lockTime": null,
                    "refund": 1,
                    "refundTime": null,
                    "delay": 1,
                    "delayOverTime": null,
                    "evaluate": 1,
                    "sellerEvaluate": 2,
                    "afterService": 1
                }
            ],
            "pageNum": 1,
            "pageSize": 1,
            "totalNum": 19,
            "totalPageNum": 19
        }
    }
}